version: '3.1'

services:

    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports:
            - "5432:5432"

        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
